server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    discovery:
      client:
        simple:
          instances:
            login:
              - uri: http://localhost:8082
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers, RETAIN_FIRST
      routes:
        - id: login
          uri: lb://login
          predicates:
            - Path=/v1/**, /login/**, /auth/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: true

  cors:
    url:
      - http://localhost:8081
      - http://localhost:3000
      - https://localhost:3000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG